eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: salman
spring:
  cloud:
    config:
      override-system-properties: false
management:
  tracing:
    sampling:
      probability: 1.0

application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 604800000