server:
  port: 8766

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
