server:
  port: 8081
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/login
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/me
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/team/**
        - id: citizen-service
          uri: lb://CITIZEN-SERVICE
          predicates:
            - Path=/api/citizen/**

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/category/**

        - id: hospital-service
          uri: lb://HOSPITAL-SERVICE
          predicates:
            - Path=/api/hospital/**

        - id: emergency-service
          uri: lb://EMERGENCY-SERVICE
          predicates:
            - Path=/api/emergency/**

        - id: standard-service
          uri: lb://STANDARD-SERVICE
          predicates:
            - Path=/api/standard/**



            
