server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/login
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/me
            
