server:
  port: 8767

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
